### ISSUE TITLE
По поводу работы

### ISSUE THREAD

**Issue by Dmitryi** [sergei-silnov/sergei-silnov.github.io#1]
Здравствуйте, Алексей.
Заранее извиняюсь, что пишу в github.
Я Дмитрий. 28 августа на вашу почту отправлял вакансии Ruby on Rails dev.
Хочу узнать вы готовы рассмотреть предложение о работе?

**Comment by kumekay** [comment]
Добрый день. Меня зовут Сергей. Предложения сейчас неинтересны
